kafka:
  brokers: "164.52.202.184:9092"
  topic: "entity-change-events-1"
  groupId: "flink-cdc-group-l1222k222Kk2m2lkkkkl-slsl--m;9--000"
  readFromEarliest: false

iceberg:
  warehouse: "s3://sc-developer-bucket/iceberg_db_test.db"
  catalog-name: "glue_catalog"
  catalog-type: "glue"
  io-impl: "org.apache.iceberg.aws.s3.S3FileIO"
  aws-region: "ap-south-1"
  database: "iceberg_db_test"
  table: "ck_orders"
  # Dynamic LOB routing: Add new LOBs here without code changes
  # Each LOB will create a table named ck_orders_{lob}
  known-lobs:
    - niineuat
    - simamyuat

